//
// Created by moritzmg on 14/01/18.
//

#ifndef GST_RTSP_SERVER_GSTRTSPMEDIAFACTORYCUSTOM_H
#define GST_RTSP_SERVER_GSTRTSPMEDIAFACTORYCUSTOM_H

#endif //GST_RTSP_SERVER_GSTRTSPMEDIAFACTORYCUSTOM_H
