/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDial>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "qvideowidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *stackedWidgetPage1;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLineEdit *lineEdit;
    QPushButton *pushButton_12;
    QWidget *page_2;
    QListWidget *listWidget;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QListWidget *listWidget_2;
    QListWidget *listWidget_3;
    QProgressBar *progressBar;
    QProgressBar *progressBar_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_11;
    QLabel *label_5;
    QLabel *label_6;
    QWidget *page_3;
    QDial *dial_13;
    QSlider *horizontalSlider;
    QDial *dial_11;
    QDial *dial_8;
    QDial *dial_3;
    QDial *dial_9;
    QDial *dial_2;
    QDial *dial_6;
    QDial *dial_5;
    QDial *dial_7;
    QDial *dial;
    QSlider *verticalSlider;
    QDial *dial_12;
    QSlider *verticalSlider_2;
    QDial *dial_4;
    QDial *dial_10;
    QPushButton *pushButton_4;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QWidget *page_4;
    QPushButton *pushButton_5;
    QVideoWidget *widget;
    QWidget *page;
    QPushButton *pushButton_6;
    QDial *dial_14;
    QDial *dial_17;
    QDial *dial_18;
    QVideoWidget *widget_2;
    QVideoWidget *widget_3;
    QSlider *horizontalSlider_2;
    QVideoWidget *widget_4;
    QDial *dial_15;
    QDial *dial_19;
    QDial *dial_20;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(597, 422);
        QSizePolicy sizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(107, 107, 107, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        MainWindow->setPalette(palette);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, -1, 561, 341));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(stackedWidget->sizePolicy().hasHeightForWidth());
        stackedWidget->setSizePolicy(sizePolicy1);
        stackedWidget->setAutoFillBackground(false);
        stackedWidgetPage1 = new QWidget();
        stackedWidgetPage1->setObjectName(QStringLiteral("stackedWidgetPage1"));
        pushButton_7 = new QPushButton(stackedWidgetPage1);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(30, 70, 192, 108));
        pushButton_7->setIconSize(QSize(16, 9));
        pushButton_8 = new QPushButton(stackedWidgetPage1);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(340, 70, 192, 108));
        pushButton_9 = new QPushButton(stackedWidgetPage1);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(30, 230, 192, 108));
        pushButton_10 = new QPushButton(stackedWidgetPage1);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(340, 230, 192, 108));
        lineEdit = new QLineEdit(stackedWidgetPage1);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(230, 10, 113, 20));
        pushButton_12 = new QPushButton(stackedWidgetPage1);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(240, 40, 81, 23));
        pushButton_12->setCursor(QCursor(Qt::PointingHandCursor));
        stackedWidget->addWidget(stackedWidgetPage1);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        listWidget = new QListWidget(page_2);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(10, 40, 131, 261));
        listWidget->setDragEnabled(true);
        listWidget->setDragDropMode(QAbstractItemView::DragOnly);
        pushButton = new QPushButton(page_2);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 310, 131, 23));
        pushButton_2 = new QPushButton(page_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 10, 131, 23));
        listWidget_2 = new QListWidget(page_2);
        listWidget_2->setObjectName(QStringLiteral("listWidget_2"));
        listWidget_2->setGeometry(QRect(160, 121, 171, 171));
        listWidget_2->setDragEnabled(true);
        listWidget_2->setDragDropMode(QAbstractItemView::DragDrop);
        listWidget_2->setDefaultDropAction(Qt::MoveAction);
        listWidget_3 = new QListWidget(page_2);
        listWidget_3->setObjectName(QStringLiteral("listWidget_3"));
        listWidget_3->setGeometry(QRect(380, 121, 171, 171));
        listWidget_3->setDragEnabled(true);
        listWidget_3->setDragDropMode(QAbstractItemView::DragDrop);
        listWidget_3->setDefaultDropAction(Qt::MoveAction);
        progressBar = new QProgressBar(page_2);
        progressBar->setObjectName(QStringLiteral("progressBar"));
        progressBar->setGeometry(QRect(160, 60, 171, 23));
        progressBar->setCursor(QCursor(Qt::PointingHandCursor));
        progressBar->setMouseTracking(true);
        progressBar->setValue(24);
        progressBar->setTextVisible(false);
        progressBar_2 = new QProgressBar(page_2);
        progressBar_2->setObjectName(QStringLiteral("progressBar_2"));
        progressBar_2->setGeometry(QRect(380, 60, 171, 23));
        progressBar_2->setCursor(QCursor(Qt::PointingHandCursor));
        progressBar_2->setMouseTracking(true);
        progressBar_2->setValue(24);
        progressBar_2->setTextVisible(false);
        pushButton_3 = new QPushButton(page_2);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(500, 10, 51, 31));
        pushButton_11 = new QPushButton(page_2);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(280, 310, 151, 23));
        label_5 = new QLabel(page_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(160, 90, 171, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush2(QColor(120, 120, 120, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        label_5->setPalette(palette1);
        label_6 = new QLabel(page_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(386, 90, 161, 20));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        page_3->setAutoFillBackground(false);
        dial_13 = new QDial(page_3);
        dial_13->setObjectName(QStringLiteral("dial_13"));
        dial_13->setGeometry(QRect(250, 130, 50, 64));
        dial_13->setMaximum(127);
        horizontalSlider = new QSlider(page_3);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(200, 50, 160, 22));
        horizontalSlider->setMaximum(127);
        horizontalSlider->setValue(63);
        horizontalSlider->setOrientation(Qt::Horizontal);
        dial_11 = new QDial(page_3);
        dial_11->setObjectName(QStringLiteral("dial_11"));
        dial_11->setGeometry(QRect(410, 130, 31, 31));
        QPalette palette2;
        QBrush brush3(QColor(0, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        QBrush brush4(QColor(85, 85, 255, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush4);
        QBrush brush5(QColor(213, 213, 255, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush5);
        QBrush brush6(QColor(149, 149, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        QBrush brush7(QColor(42, 42, 127, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush7);
        QBrush brush8(QColor(56, 56, 170, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        QBrush brush9(QColor(170, 170, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        QBrush brush10(QColor(255, 255, 220, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_11->setPalette(palette2);
        dial_11->setMaximum(127);
        dial_8 = new QDial(page_3);
        dial_8->setObjectName(QStringLiteral("dial_8"));
        dial_8->setGeometry(QRect(330, 190, 31, 31));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_8->setPalette(palette3);
        dial_8->setMaximum(127);
        dial_3 = new QDial(page_3);
        dial_3->setObjectName(QStringLiteral("dial_3"));
        dial_3->setGeometry(QRect(180, 130, 31, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        QBrush brush11(QColor(255, 67, 30, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush11);
        QBrush brush12(QColor(255, 174, 158, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush12);
        QBrush brush13(QColor(255, 120, 94, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        QBrush brush14(QColor(127, 33, 15, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush14);
        QBrush brush15(QColor(170, 44, 20, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        QBrush brush16(QColor(255, 161, 142, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_3->setPalette(palette4);
        dial_3->setMaximum(127);
        dial_9 = new QDial(page_3);
        dial_9->setObjectName(QStringLiteral("dial_9"));
        dial_9->setGeometry(QRect(410, 190, 31, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_9->setPalette(palette5);
        dial_9->setMaximum(127);
        dial_2 = new QDial(page_3);
        dial_2->setObjectName(QStringLiteral("dial_2"));
        dial_2->setGeometry(QRect(140, 130, 31, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush12);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush14);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_2->setPalette(palette6);
        dial_2->setMaximum(127);
        dial_6 = new QDial(page_3);
        dial_6->setObjectName(QStringLiteral("dial_6"));
        dial_6->setGeometry(QRect(180, 190, 31, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush12);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush14);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_6->setPalette(palette7);
        dial_6->setMaximum(127);
        dial_5 = new QDial(page_3);
        dial_5->setObjectName(QStringLiteral("dial_5"));
        dial_5->setGeometry(QRect(140, 190, 31, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush12);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush14);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_5->setPalette(palette8);
        dial_5->setMaximum(127);
        dial_7 = new QDial(page_3);
        dial_7->setObjectName(QStringLiteral("dial_7"));
        dial_7->setGeometry(QRect(330, 130, 31, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_7->setPalette(palette9);
        dial_7->setMaximum(127);
        dial = new QDial(page_3);
        dial->setObjectName(QStringLiteral("dial"));
        dial->setGeometry(QRect(100, 130, 31, 31));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush12);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush14);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial->setPalette(palette10);
        dial->setMaximum(127);
        verticalSlider = new QSlider(page_3);
        verticalSlider->setObjectName(QStringLiteral("verticalSlider"));
        verticalSlider->setGeometry(QRect(140, 240, 22, 81));
        verticalSlider->setMaximum(100);
        verticalSlider->setSingleStep(1);
        verticalSlider->setOrientation(Qt::Vertical);
        dial_12 = new QDial(page_3);
        dial_12->setObjectName(QStringLiteral("dial_12"));
        dial_12->setGeometry(QRect(370, 190, 31, 31));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush4);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_12->setPalette(palette11);
        dial_12->setMaximum(127);
        verticalSlider_2 = new QSlider(page_3);
        verticalSlider_2->setObjectName(QStringLiteral("verticalSlider_2"));
        verticalSlider_2->setGeometry(QRect(380, 240, 22, 81));
        verticalSlider_2->setMaximum(127);
        verticalSlider_2->setOrientation(Qt::Vertical);
        dial_4 = new QDial(page_3);
        dial_4->setObjectName(QStringLiteral("dial_4"));
        dial_4->setGeometry(QRect(100, 190, 31, 31));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush11);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush12);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush14);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush15);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush11);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush16);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush12);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush15);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush15);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_4->setPalette(palette12);
        dial_4->setMaximum(127);
        dial_10 = new QDial(page_3);
        dial_10->setObjectName(QStringLiteral("dial_10"));
        dial_10->setGeometry(QRect(370, 130, 31, 31));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush8);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_10->setPalette(palette13);
        dial_10->setMaximum(127);
        pushButton_4 = new QPushButton(page_3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(500, 10, 51, 31));
        label = new QLabel(page_3);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(130, 170, 47, 13));
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(page_3);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(370, 170, 47, 13));
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(page_3);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(106, 110, 101, 20));
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(page_3);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(340, 110, 101, 20));
        label_4->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        pushButton_5 = new QPushButton(page_4);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(500, 10, 51, 31));
        widget = new QVideoWidget(page_4);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(9, 49, 551, 281));
        sizePolicy1.setHeightForWidth(widget->sizePolicy().hasHeightForWidth());
        widget->setSizePolicy(sizePolicy1);
        stackedWidget->addWidget(page_4);
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        pushButton_6 = new QPushButton(page);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(500, 10, 51, 31));
        dial_14 = new QDial(page);
        dial_14->setObjectName(QStringLiteral("dial_14"));
        dial_14->setGeometry(QRect(70, 220, 50, 51));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        QBrush brush17(QColor(0, 170, 0, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush17);
        QBrush brush18(QColor(0, 255, 0, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush18);
        QBrush brush19(QColor(0, 212, 0, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush19);
        QBrush brush20(QColor(0, 85, 0, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush20);
        QBrush brush21(QColor(0, 113, 0, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush21);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        QBrush brush22(QColor(127, 212, 127, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush22);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush18);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush19);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush20);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush21);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush22);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush20);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush18);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush19);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush20);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush21);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush20);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush20);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_14->setPalette(palette14);
        dial_14->setMaximum(127);
        dial_17 = new QDial(page);
        dial_17->setObjectName(QStringLiteral("dial_17"));
        dial_17->setGeometry(QRect(70, 160, 50, 51));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        QBrush brush23(QColor(255, 0, 0, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush23);
        QBrush brush24(QColor(255, 127, 127, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush24);
        QBrush brush25(QColor(255, 63, 63, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush25);
        QBrush brush26(QColor(127, 0, 0, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush26);
        QBrush brush27(QColor(170, 0, 0, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush27);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush23);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush24);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush23);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush24);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush25);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush26);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush27);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush23);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush24);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush26);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush23);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush24);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush25);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush26);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush27);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush26);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush26);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush23);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush23);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush23);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_17->setPalette(palette15);
        dial_17->setMaximum(127);
        dial_18 = new QDial(page);
        dial_18->setObjectName(QStringLiteral("dial_18"));
        dial_18->setGeometry(QRect(70, 280, 50, 51));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        QBrush brush28(QColor(0, 0, 255, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush28);
        QBrush brush29(QColor(127, 127, 255, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush29);
        QBrush brush30(QColor(63, 63, 255, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush30);
        QBrush brush31(QColor(0, 0, 127, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush31);
        QBrush brush32(QColor(0, 0, 170, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette16.setBrush(QPalette::Active, QPalette::Mid, brush32);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush28);
        palette16.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette16.setBrush(QPalette::Active, QPalette::AlternateBase, brush29);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush28);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush29);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush30);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush31);
        palette16.setBrush(QPalette::Inactive, QPalette::Mid, brush32);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush28);
        palette16.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush29);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush31);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush28);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush29);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush30);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush31);
        palette16.setBrush(QPalette::Disabled, QPalette::Mid, brush32);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush31);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush31);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush28);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush28);
        palette16.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush28);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_18->setPalette(palette16);
        dial_18->setMaximum(127);
        widget_2 = new QVideoWidget(page);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(210, 50, 141, 81));
        widget_3 = new QVideoWidget(page);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(30, 50, 141, 81));
        horizontalSlider_2 = new QSlider(page);
        horizontalSlider_2->setObjectName(QStringLiteral("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(210, 280, 160, 22));
        horizontalSlider_2->setMaximum(127);
        horizontalSlider_2->setValue(63);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        widget_4 = new QVideoWidget(page);
        widget_4->setObjectName(QStringLiteral("widget_4"));
        widget_4->setGeometry(QRect(380, 50, 141, 81));
        dial_15 = new QDial(page);
        dial_15->setObjectName(QStringLiteral("dial_15"));
        dial_15->setGeometry(QRect(420, 220, 50, 51));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush17);
        palette17.setBrush(QPalette::Active, QPalette::Light, brush18);
        palette17.setBrush(QPalette::Active, QPalette::Midlight, brush19);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush20);
        palette17.setBrush(QPalette::Active, QPalette::Mid, brush21);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette17.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush17);
        palette17.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette17.setBrush(QPalette::Active, QPalette::AlternateBase, brush22);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush17);
        palette17.setBrush(QPalette::Inactive, QPalette::Light, brush18);
        palette17.setBrush(QPalette::Inactive, QPalette::Midlight, brush19);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush20);
        palette17.setBrush(QPalette::Inactive, QPalette::Mid, brush21);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush17);
        palette17.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush22);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush20);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush17);
        palette17.setBrush(QPalette::Disabled, QPalette::Light, brush18);
        palette17.setBrush(QPalette::Disabled, QPalette::Midlight, brush19);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush20);
        palette17.setBrush(QPalette::Disabled, QPalette::Mid, brush21);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush20);
        palette17.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush20);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush17);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush17);
        palette17.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette17.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush17);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_15->setPalette(palette17);
        dial_15->setMaximum(127);
        dial_19 = new QDial(page);
        dial_19->setObjectName(QStringLiteral("dial_19"));
        dial_19->setGeometry(QRect(420, 280, 50, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush28);
        palette18.setBrush(QPalette::Active, QPalette::Light, brush29);
        palette18.setBrush(QPalette::Active, QPalette::Midlight, brush30);
        palette18.setBrush(QPalette::Active, QPalette::Dark, brush31);
        palette18.setBrush(QPalette::Active, QPalette::Mid, brush32);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette18.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush28);
        palette18.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette18.setBrush(QPalette::Active, QPalette::AlternateBase, brush29);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush28);
        palette18.setBrush(QPalette::Inactive, QPalette::Light, brush29);
        palette18.setBrush(QPalette::Inactive, QPalette::Midlight, brush30);
        palette18.setBrush(QPalette::Inactive, QPalette::Dark, brush31);
        palette18.setBrush(QPalette::Inactive, QPalette::Mid, brush32);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush28);
        palette18.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush29);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush31);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush28);
        palette18.setBrush(QPalette::Disabled, QPalette::Light, brush29);
        palette18.setBrush(QPalette::Disabled, QPalette::Midlight, brush30);
        palette18.setBrush(QPalette::Disabled, QPalette::Dark, brush31);
        palette18.setBrush(QPalette::Disabled, QPalette::Mid, brush32);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush31);
        palette18.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush31);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush28);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush28);
        palette18.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette18.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush28);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_19->setPalette(palette18);
        dial_19->setMaximum(127);
        dial_20 = new QDial(page);
        dial_20->setObjectName(QStringLiteral("dial_20"));
        dial_20->setGeometry(QRect(420, 160, 50, 51));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush23);
        palette19.setBrush(QPalette::Active, QPalette::Light, brush24);
        palette19.setBrush(QPalette::Active, QPalette::Midlight, brush25);
        palette19.setBrush(QPalette::Active, QPalette::Dark, brush26);
        palette19.setBrush(QPalette::Active, QPalette::Mid, brush27);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette19.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush23);
        palette19.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette19.setBrush(QPalette::Active, QPalette::AlternateBase, brush24);
        palette19.setBrush(QPalette::Active, QPalette::ToolTipBase, brush10);
        palette19.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush23);
        palette19.setBrush(QPalette::Inactive, QPalette::Light, brush24);
        palette19.setBrush(QPalette::Inactive, QPalette::Midlight, brush25);
        palette19.setBrush(QPalette::Inactive, QPalette::Dark, brush26);
        palette19.setBrush(QPalette::Inactive, QPalette::Mid, brush27);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush23);
        palette19.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush24);
        palette19.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush10);
        palette19.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush26);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush23);
        palette19.setBrush(QPalette::Disabled, QPalette::Light, brush24);
        palette19.setBrush(QPalette::Disabled, QPalette::Midlight, brush25);
        palette19.setBrush(QPalette::Disabled, QPalette::Dark, brush26);
        palette19.setBrush(QPalette::Disabled, QPalette::Mid, brush27);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush26);
        palette19.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush26);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush23);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush23);
        palette19.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette19.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush23);
        palette19.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush10);
        palette19.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        dial_20->setPalette(palette19);
        dial_20->setMaximum(127);
        stackedWidget->addWidget(page);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 597, 20));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        pushButton_7->setText(QString());
        pushButton_8->setText(QString());
        pushButton_9->setText(QString());
        pushButton_10->setText(QString());
        lineEdit->setInputMask(QString());
        lineEdit->setText(QApplication::translate("MainWindow", "serveradress", nullptr));
        pushButton_12->setText(QApplication::translate("MainWindow", "confirm", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "load list", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "add file", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_11->setText(QApplication::translate("MainWindow", "Confirm lists", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Back", nullptr));
        label->setText(QApplication::translate("MainWindow", "Effects", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Effects", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "High     Mid     Low", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "High     Mid     Low", nullptr));
        pushButton_5->setText(QApplication::translate("MainWindow", "Back", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Back", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
